name: workflow

on:
  schedule:
    - cron:  "14 50 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: install MySB_dataTraffic
      run: pip3 install MySB-datatraffic
      
    - name: run MySB-datatraffic
      run: python3 test.py
      env:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        telnum: ${{ secrets.telnum }}
        password: ${{ secrets.password }}
        line_access_token: ${{ secrets.line_access_token }}
